### ISSUE TITLE
Incorporate RSS

### ISSUE THREAD

**Issue by mbaz** [kyledrake/neocities-web#18]
Reading recent articles about Google Reader and RSS, it occurred to me that having some sort of RSS support incorporated into neocities would be very attractive. I haven't really thought this through; I just want to toss the ideas out there and see if something sticks.

- The owner of a neocities page could choose to have an 'automatic RSS' feed, where any change to the pages updates the RSS feed, with an optional comment. This feed would have an easy to find URL, maybe 'neocities.org/mypage/feed' or similar.

- The owner could also have an automatically generated 'Public Feeds' page (maybe limited to neocities feeds?), where feeds of his choosing can be read, with a very simple interface.

One of the selling points of the walled gardens is automatic interconections between users. Neocities could implement something similar using RSS.

I hope you find these ideas of some interest!

**Comment by kyledrake** [comment]
There is RSS now, see the new Neocities
